In [1]:
import torch

In [2]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])

In [3]:
print(x.shape)

torch.Size([2, 4])


In [4]:
x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [5]:
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [6]:
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [7]:
x.shape

torch.Size([2, 4])

In [8]:
x.view(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [9]:
a = torch.ones(2, 1, 10)

In [10]:
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [12]:
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.squeeze(1)
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 1, 10])
This is the shape after squeezing torch.Size([2, 10])


In [13]:
a = torch.ones(2, 2, 10)
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.squeeze(1)
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 2, 10])
This is the shape after squeezing torch.Size([2, 2, 10])


In [15]:
a = torch.ones(2, 3, 1)
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.squeeze(2)
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 3, 1])
This is the shape after squeezing torch.Size([2, 3])


In [16]:
a = torch.ones(2,3)
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.unsqueeze(2)
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 3])
This is the shape after squeezing torch.Size([2, 3, 1])


In [17]:
a = torch.ones(2,3)

In [18]:
print(a[None].shape)
print(a[:,None].shape)
print(a[:,:,None].shape)

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])
