In [1]:
import torch

In [2]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])  # matriz 2x4

In [3]:
print(x.shape)

torch.Size([2, 4])


In [ ]:
x*10  # operação elemento a elemento igual numpy

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [ ]:
x.add(10)  # forma orientada a objeto de somar

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [ ]:
x  # x continua igual, o .add() lá de cima nao mudou nada

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [7]:
x.shape

torch.Size([2, 4])

In [ ]:
x.view(4,2)  # equivalente ao reshape, muda so o formato de leitura

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [ ]:
a = torch.ones(2, 1, 10)  # tensor preenchido de 1, shape (2,1,10)

In [10]:
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [ ]:
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.squeeze(1)  # squeeze remove uma dimensão se ela tiver tamanho 1 aqui a dim 1 tem tamanho 1 entao some
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 1, 10])
This is the shape after squeezing torch.Size([2, 10])


In [ ]:
a = torch.ones(2, 2, 10)
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.squeeze(1)  # aqui a dim 1 tem tamanho 2, nao 1 ent o squeeze nao faz nada e o shape continua igual
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 2, 10])
This is the shape after squeezing torch.Size([2, 2, 10])


In [ ]:
a = torch.ones(2, 3, 1)
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.squeeze(2)  # ultima dim tem tamanho 1 ent some e sobra (2,3)
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 3, 1])
This is the shape after squeezing torch.Size([2, 3])


In [ ]:
a = torch.ones(2,3)
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.unsqueeze(2)  # unsqueeze é o contrário adiciona uma dimensao de tamanho 1 na posição indicada
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 3])
This is the shape after squeezing torch.Size([2, 3, 1])


In [17]:
a = torch.ones(2,3)

In [ ]:
# indexar com None é um atalho pro unsqueeze(0), vira (1,2,3)
print(a[None].shape)
# None na posição 1 unsqueeze(1) vira (2,1,3)
print(a[:,None].shape)
# None na posição 2 unsqueeze(2) vira (2,3,1)
print(a[:,:,None].shape)

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])
